name = "hmt-frontend-toy"
homepage = "https://hummanta.github.io/hmt-frontend-toy"
repository = "https://github.com/hummanta/hmt-frontend-toy"
language = "Toy"
kind = "frontend"
description = "Parsing the Toy source code and generating the Cranelift IR"
targets = [
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "aarch64-apple-darwin",
    "x86_64-pc-windows-msvc",
]
latest = "v0.6.8"

[releases]
"v0.6.5" = "release-v0.6.5.toml"
"v0.5.0" = "release-v0.5.0.toml"
"v0.6.0" = "release-v0.6.0.toml"
"v0.1.0" = "release-v0.1.0.toml"
"v0.6.7" = "release-v0.6.7.toml"
"v0.2.0" = "release-v0.2.0.toml"
"v0.6.8" = "release-v0.6.8.toml"
"v0.4.0" = "release-v0.4.0.toml"
"v0.6.4" = "release-v0.6.4.toml"
"v0.3.0" = "release-v0.3.0.toml"
"v0.6.2" = "release-v0.6.2.toml"
"v0.6.6" = "release-v0.6.6.toml"
"v0.6.1" = "release-v0.6.1.toml"
"v0.6.3" = "release-v0.6.3.toml"
