version = "v0.6.5"

[artifacts.x86_64-unknown-linux-gnu]
url = "https://github.com/hummanta/hmt-frontend-toy/releases/download/v0.6.5/hmt-frontend-toy-v0.6.5-x86_64-unknown-linux-gnu.tar.gz"
hash = "99e44e6f75d1d91a34364806b182502528a34285e877e9b88a40fe2e35c01375"

[artifacts.aarch64-unknown-linux-gnu]
url = "https://github.com/hummanta/hmt-frontend-toy/releases/download/v0.6.5/hmt-frontend-toy-v0.6.5-aarch64-unknown-linux-gnu.tar.gz"
hash = "d5253233d33c94eeaca5988015c9eff7563d30dbf5a911c7a7efafd18ca7a60f"

[artifacts.aarch64-apple-darwin]
url = "https://github.com/hummanta/hmt-frontend-toy/releases/download/v0.6.5/hmt-frontend-toy-v0.6.5-aarch64-apple-darwin.tar.gz"
hash = "c507587c9483f971c1d72abbb04f28b4a7a63b5ebaebdd11004d84cbf5d6b0e3"

[artifacts.x86_64-apple-darwin]
url = "https://github.com/hummanta/hmt-frontend-toy/releases/download/v0.6.5/hmt-frontend-toy-v0.6.5-x86_64-apple-darwin.tar.gz"
hash = "b3bf988f0453212735bf7fc63cec904f9429b93a2384ceb356a8fcc5b800e326"

[artifacts.x86_64-pc-windows-msvc]
url = "https://github.com/hummanta/hmt-frontend-toy/releases/download/v0.6.5/hmt-frontend-toy-v0.6.5-x86_64-pc-windows-msvc.tar.gz"
hash = "f51a61ec09bc52125027d8a95f16728da3700e3b353efb0bb43bfa8b36cf8380"
