version = "v0.6.10"

[artifacts.aarch64-unknown-linux-gnu]
url = "https://github.com/hummanta/hmt-frontend-toy/releases/download/v0.6.10/hmt-frontend-toy-v0.6.10-aarch64-unknown-linux-gnu.tar.gz"
hash = "04aedee3114e62a7b275241c193113aa22bbdc113a83a56c1ef68b4aac817868"

[artifacts.x86_64-pc-windows-msvc]
url = "https://github.com/hummanta/hmt-frontend-toy/releases/download/v0.6.10/hmt-frontend-toy-v0.6.10-x86_64-pc-windows-msvc.tar.gz"
hash = "11a357c19cb3b725034f7c5832b96d1707101943853ff2a44896d5ff38b75f07"

[artifacts.x86_64-unknown-linux-gnu]
url = "https://github.com/hummanta/hmt-frontend-toy/releases/download/v0.6.10/hmt-frontend-toy-v0.6.10-x86_64-unknown-linux-gnu.tar.gz"
hash = "8b5677b9b51c69c6d92a9f11fad91066d126a4433f1da8c92b36ee943ea3a1b3"

[artifacts.x86_64-apple-darwin]
url = "https://github.com/hummanta/hmt-frontend-toy/releases/download/v0.6.10/hmt-frontend-toy-v0.6.10-x86_64-apple-darwin.tar.gz"
hash = "315dd9204bddf7f35ee1c997b24ce472b6d17c6eea1ee14e02df6ae67d408f42"

[artifacts.aarch64-apple-darwin]
url = "https://github.com/hummanta/hmt-frontend-toy/releases/download/v0.6.10/hmt-frontend-toy-v0.6.10-aarch64-apple-darwin.tar.gz"
hash = "c83ce5079c5a9233d0939a4e09a90efb87e0270a9918cd66b21f9b19e4251b46"
