version = "v0.2.0"

[artifacts.aarch64-unknown-linux-gnu]
url = "https://github.com/hummanta/hmt-frontend-toy/releases/download/v0.2.0/hmt-frontend-toy-v0.2.0-aarch64-unknown-linux-gnu.tar.gz"
hash = "71a8284c778206fa6c07aecf1ecc5c48c95965fb807e7fbde2f67df1255cbba5"

[artifacts.aarch64-apple-darwin]
url = "https://github.com/hummanta/hmt-frontend-toy/releases/download/v0.2.0/hmt-frontend-toy-v0.2.0-aarch64-apple-darwin.tar.gz"
hash = "2d1764aadd2a8ae6c5e055d7df32d1ec2d3f911a9a57b54297c887b585aca901"

[artifacts.x86_64-pc-windows-msvc]
url = "https://github.com/hummanta/hmt-frontend-toy/releases/download/v0.2.0/hmt-frontend-toy-v0.2.0-x86_64-pc-windows-msvc.tar.gz"
hash = "6d9aed9a27cc4b8d3d4e38a0d1f26273842beb653214d2f1b6f09a8d111d1107"

[artifacts.x86_64-unknown-linux-gnu]
url = "https://github.com/hummanta/hmt-frontend-toy/releases/download/v0.2.0/hmt-frontend-toy-v0.2.0-x86_64-unknown-linux-gnu.tar.gz"
hash = "79497f3dec5237ba5814a6ea1b4ad77d6260588719c98aa6c3b7c590c19b6195"

[artifacts.x86_64-apple-darwin]
url = "https://github.com/hummanta/hmt-frontend-toy/releases/download/v0.2.0/hmt-frontend-toy-v0.2.0-x86_64-apple-darwin.tar.gz"
hash = "a416a2f0dca2a057945ff7abdbd2cc37bf5a5f09e551b366d73721837f9c9879"
